

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "5000:5000"
    volumes:
      - pewpew_data:/data
    environment:
      - FLASK_ENV=development
      - DATABASE_DIR=/data
    user: "1000:1000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"  # Changed external port to 8000  - everyting always uses 8080!! haha
    depends_on:
      - api

volumes:
  pewpew_data:
